version: "3"
services:
  ali-nacos:
    image: nacos/nacos-server:2.0.0
    container_name: ali-nacos
    hostname: ali-nacos
    env_file:
      - ./nacos/nacos-standlone-mysql.env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8848:8848
      - 9555:9555
    depends_on:
      - ali-mysql
    restart: always
    networks:
      - cloud_alibaba
  ali-mysql:
    image: nacos/nacos-mysql:8.0.16
    container_name: ali-mysql
    hostname: ali-mysql
    env_file:
      - ./mysql/mysql.env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    networks:
      - cloud_alibaba
      
  ali-sentinel:
    image: bladex/sentinel-dashboard:1.8.0
    container_name: ali-sentinel
    hostname: ali-sentinel
    ports:
      - 8858:8858
    environment:
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - cloud_alibaba
    
  ali-seata:
    image: seataio/seata-server:1.4.1
    container_name: ali-seata
    hostname: ali-server
    ports:
      - 8091:8091
    environment:
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
      - SEATA_IP=127.0.0.1
      - SEATA_PORT=8091
      - TZ=Asia/Shanghai
    volumes:
      - ./seata/config:/root/seata-config
    depends_on:
      - ali-mysql
      - ali-nacos
    restart: always
    networks:
      - cloud_alibaba
    
networks:
  cloud_alibaba:
    external:
      name: cloud_alibaba
